name: Ebuild Tests

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: hacking-gentoo/action-ebuild-test@master
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
